-- Supabase에서 댓글을 저장할 comments 테이블을 생성합니다.
-- users와 posts 테이블을 먼저 생성한 후 실행해야 합니다.

CREATE TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_comments_post
        FOREIGN KEY (post_id)
        REFERENCES posts(post_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_comments_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- 테스트용 댓글 데이터 10개
-- -----------------------------------------------------------------------------
-- users와 posts 테이블에 테스트 데이터가 각각 10개 이상 있다고 가정합니다.
-- 실제 ID가 1~10이 아니어도 각 테이블의 앞 10개 데이터를 순서대로 연결합니다.
-- 같은 게시글, 사용자, 내용의 댓글이 이미 있으면 중복으로 추가하지 않습니다.

WITH numbered_users AS (
    SELECT
        user_id,
        ROW_NUMBER() OVER (ORDER BY user_id) AS row_number
    FROM users
    ORDER BY user_id
    LIMIT 10
),
numbered_posts AS (
    SELECT
        post_id,
        ROW_NUMBER() OVER (ORDER BY post_id) AS row_number
    FROM posts
    ORDER BY post_id
    LIMIT 10
),
sample_comments (row_number, content) AS (
    VALUES
        (1, '첫 번째 게시글의 테스트 댓글입니다.'),
        (2, '게시글 내용이 이해하기 쉽게 작성되어 있습니다.'),
        (3, '좋은 정보 감사합니다.'),
        (4, '이 부분을 조금 더 자세히 알고 싶습니다.'),
        (5, '저도 같은 생각입니다.'),
        (6, '게시글별 댓글 조회 테스트입니다.'),
        (7, '댓글 한 건 조회 테스트입니다.'),
        (8, '댓글 수정 API 테스트에 사용할 댓글입니다.'),
        (9, '댓글 삭제 API 테스트에 사용할 댓글입니다.'),
        (10, 'Supabase와 FastAPI 연결 확인용 댓글입니다.')
)
INSERT INTO comments (post_id, user_id, content)
SELECT
    numbered_posts.post_id,
    numbered_users.user_id,
    sample_comments.content
FROM sample_comments
JOIN numbered_users USING (row_number)
JOIN numbered_posts USING (row_number)
WHERE NOT EXISTS (
    SELECT 1
    FROM comments
    WHERE comments.post_id = numbered_posts.post_id
      AND comments.user_id = numbered_users.user_id
      AND comments.content = sample_comments.content
);

-- 입력된 댓글을 최신순으로 확인합니다.
SELECT
    comment_id,
    post_id,
    user_id,
    content,
    created_at,
    updated_at
FROM comments
ORDER BY comment_id DESC;
