-- 실행 방법: Supabase Dashboard의 SQL Editor에 이 파일 내용을 붙여 넣고 Run을 누릅니다.
-- 선행 조건: 계획서의 users.sql을 먼저 실행해 users 테이블을 생성해야 합니다.

CREATE TABLE IF NOT EXISTS posts (
    post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_posts_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

-- 예제 데이터 10개
-- 아래 데이터는 users 테이블에 user_id 1~5가 존재할 때 실행할 수 있습니다.
-- 같은 예제 데이터가 중복으로 들어가지 않도록 비어 있는 posts 테이블에서 한 번만 실행하세요.
INSERT INTO posts (user_id, title, content) VALUES
    (1, 'FastAPI 프로젝트를 시작합니다',
     'FastAPI의 기본 구조를 익히고 게시판 API 개발을 시작했습니다.'),
    (2, 'Pydantic으로 요청 데이터 검증하기',
     '게시글 제목과 내용의 길이를 Pydantic Field를 사용해 검증하는 방법을 정리했습니다.'),
    (3, 'Supabase 프로젝트 연결 후기',
     '환경 변수로 Supabase 접속 정보를 관리하고 Python 클라이언트를 연결했습니다.'),
    (4, '게시글 생성 API 구현 완료',
     'POST /posts 경로에서 새로운 게시글을 등록하는 기능을 구현했습니다.'),
    (5, '게시글 목록 조회 기능 공유',
     'GET /posts 요청으로 최신 게시글 목록을 조회할 수 있도록 구현했습니다.'),
    (1, '게시글 상세 조회 시 404 처리',
     '존재하지 않는 게시글을 조회하면 404 응답을 반환하도록 예외 처리를 추가했습니다.'),
    (2, '게시글 수정 API 테스트 결과',
     'PUT /posts/{post_id} 요청으로 제목과 내용이 정상적으로 수정되는 것을 확인했습니다.'),
    (3, '게시글 삭제 기능 구현하기',
     'DELETE 요청을 처리하고 삭제된 게시글 번호를 응답하도록 구성했습니다.'),
    (4, 'Swagger UI로 API 확인하기',
     '서버 실행 후 /docs에서 게시글 CRUD API를 직접 호출해 보았습니다.'),
    (5, 'pytest로 게시판 API 검증하기',
     '정상 요청과 입력값 오류, 존재하지 않는 게시글 응답을 pytest로 테스트했습니다.');
