


CREATE TABLE IF NOT EXISTS supports (
    support_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_support_status
        CHECK (status IN ('pending', 'answered', 'closed')),
    CONSTRAINT fk_supports_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

-- 예제 데이터 10건
INSERT INTO supports (id, title, content, create_at) VALUES
    ('20260722090000000001', '기본 티셔츠', 안녕, '2026-07-22 09:00:00'),
    ('20260722090500000002', '청바지', hello, '2026-07-22 09:05:00'),
    ('20260722091000000003', '후드 집업', 반가워, '2026-07-22 09:10:00'),
    ('20260722091500000004', '운동화', 배고파, '2026-07-22 09:15:00'),
    ('20260722092000000005', '캔버스 백', 커피, '2026-07-22 09:20:00'),
    ('20260722092500000006', '볼캡', 18000, '2026-07-22 09:25:00'),
    ('20260722093000000007', '양말 3팩', 12000, '2026-07-22 09:30:00'),
    ('20260722093500000008', '코튼 셔츠', 39000, '2026-07-22 09:35:00'),
    ('20260722094000000009', '니트 가디건', 65000, '2026-07-22 09:40:00'),
    ('20260722094500000010', '데님 재킷', 88000, '2026-07-22 09:45:00');
